services:
  app:
    build: .
    container_name: meteor-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /tmp/vite-cache
    depends_on:
      - mysql
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - METEOR_DISABLE_OPTIMISTIC_CACHING=1
      - VUE_HOT_RELOAD=true

  mysql:
    image: mysql:8.4
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meteor_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  node_modules:
  vite_cache:
